### ISSUE TITLE
Automatically changed slots (overnight)

### ISSUE THREAD

**Issue by csestonia** [GameServerManagers/LinuxGSM-Support#31]
All my 4 servers changed automatically slots. I dont know why and how but for example server with 36 slots changed to 16 slots.
The lgsm main config is in place and fine, but still less slots. Also from today and yesterday ther is 1 extra cfg file called “.cfg”. Maybe this is the issue and why its there, its blank but why it generated?

**Comment by csestonia** [comment]
I found a temporary fix. I copied all my text from my personal instance setting cfg file that I used for a years, to cfg named “.cfg” and everything started working. 
I also tried to do “./csgoserver validate” to see, will it overwrite or no. And it did not overwrite. So
This is the quick fix, if someone need. 


But still I need an answer why it did by itself like that.

**Comment by antonybrago** [comment]
I have the same problem with my several CS:GO servers

**Comment by kennyLtv** [comment]
Try updating your LGSM after yesterdays release there was a missed variable name change in the instance config check. The `servicename` was deprecated in favor of `selfname` and it was missed in one place but should be fixed now I believe.

**Comment by alphaquadrant** [comment]
I tried updating manually but it didnt solve the problem so  I renamed my "l4d2server,cfg" to ".cfg".

**Comment by dgibbs64** [comment]
ensure you run `./gameserver ul` a bug fix went out today to fix this

**Comment by alphaquadrant** [comment]
I did that a few times 1 hour ago but the problem was still there and `./gameserver dt`  kept showing 
User:                   l4d2server
Location:               /home/l4d2server
Config file:            /home/l4d2server/serverfiles/left4dead2/cfg/.cfg

I saw some files were updated:
checking function command_monitor.sh...UPDATE
checking function command_update_linuxgsm.sh...UPDATE
checking function core_dl.sh...UPDATE

I tried again right now but no change.

**Comment by dgibbs64** [comment]
can I have the output of `./l4d2server post-details`

**Comment by alphaquadrant** [comment]
https://hastebin.com/muyakuketu.sql

**Comment by alphaquadrant** [comment]
https://hastebin.com/weyuduquka.sql

**Comment by Shatten69** [comment]
> ensure you run `./gameserver ul` a bug fix went out today to fix this

All back to normal,
THANK YOU dgibbs64

---------------------------------------------------------
`./gameserver ul`
checking function core_legacy.sh...UPDATE

Before:
Config file:            /home/l4d2server/serverfiles/left4dead2/cfg/.cfg
+servercfgfile .cfg

After:
Config file:            /home/l4d2server/serverfiles/left4dead2/cfg/l4d2server.cfg
+servercfgfile l4d2server.cfg
